FIX: changing some scripts

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,8 +50,25 @@ jobs:
 
       - name: Create deployment
         run: |
-          aws deploy create-deployment \
+          OUTPUT=$(aws deploy create-deployment \
             --application-name car-rental \
             --deployment-group-name car-rental-group \
             --deployment-config-name CodeDeployDefault.OneAtATime \
-            --s3-location bucket=car-renta-deploy,key=deploy/backend/car-rental.zip,bundleType=zip
+            --s3-location bucket=car-renta-deploy,key=deploy/backend/car-rental.zip,bundleType=zip)
+          echo "deployment_id=$(echo $OUTPUT | jq -r .deploymentId)" >> $GITHUB_ENV
+
+      - name: Wait for deployment completion
+        run: |
+          DEPLOYMENT_ID=$deployment_id
+          while true; do
+            STATUS=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID | jq -r .deploymentInfo.status)
+            echo "Deployment status: $STATUS"
+            if [[ "$STATUS" == "Succeeded" ]]; then
+              echo "Deployment succeeded."
+              break
+            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Stopped" ]]; then
+              echo "Deployment failed."
+              exit 1
+            fi
+              sleep 30
+          done
